name: Publish
run-name: Publish ts-verifier from ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: [self-hosted]
    environment: production
    container:
      image: ${{ vars.AWS_ECR_REGISTRY }}/library/alpine-git-node-aws:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-publish
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref || github.sha }}

      - name: Allow Git to access repo
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Debug Git status
        run: |
          echo "PWD: $(pwd)"
          ls -la
          git status

      - name: Set Git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          echo "âœ… Git identity configured successfully."

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn build

      - name: Configure registry
        working-directory: ./
        run: |
          npm config set access public -ws=false -iwr
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPMJS_TOKEN }} -ws=false -iwr

      - name: Publish
        working-directory: ./
        run: npm publish

      - name: Send Slack message for SDK publish
        uses: slackapi/slack-github-action@v2.1.1
        env: 
          WORKFLOW_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "ts-verifier has been published to NPM\n${{ env.WORKFLOW_URL }}"